name: qa

on:
  pull_request:

jobs:
  build:
    name: Build, test and unit test validation
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
       fetch-depth: 0
       
    - name: Java setup
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
        
    - name: Build and test
      run: mvn clean install test
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
       python-version: 3.9
       
    - name: Install dependencies
      run: python -m pip install --upgrade pip
        
    - name: Install diff cover
      run: pip install diff_cover
      
    - name: Min coverage achieve?
      run: diff-cover ${{ github.workspace }}/target/jacoco-ut/jacoco.xml --compare-branch=origin/develop --fail-under=60 --exclude */Utils/*
