name: qa

on:
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: java setup
      uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
        
    - name: build and test
      run: |
       ls
       mvn clean install test
    
    - name: Upload report
      uses: 'actions/upload-artifact@v2'
      with:
        name: report.xml
        path: ${{ github.workspace }}/target/jacoco-ut/jacoco.xml
        
    - name: Upload script
      uses: 'actions/upload-artifact@v2'
      with:
        name: coverge.sh
        path: ${{ github.workspace }}/.github/workflows/scripts/coverage.sh
    
  code-coverage:
   needs: build
   name: Code coverage
   runs-on: ubuntu-latest
   steps:
    - name: download report
      uses: actions/download-artifact@v2
      with:
       name: report.xml
   
    - name: download script
      uses: actions/download-artifact@v2
      with:
       name: coverge.sh
          
    - name: Jacoco Report to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.1
      with:
        path: ${{ github.workspace }}/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 0
        min-coverage-changed-files: 60
 
    - name: Analize coverage info
      shell: bash
      run: |
       chmod +x ${{ github.workspace }}/coverage.sh
       mincoverage=60
       ${{ github.workspace }}/coverage.sh "${mincoverage}" "${{ steps.jacoco.outputs.coverage-changed-files }}"
