name: qa
on: 
  pull_request:
    branches:
      only:
      - 'feature/**'
  # Trigger the workflow on pull request,
  # but only for the feature branches

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: mvn clean install
#code-coverage:
  #steps: "diff-cover target/jacoco-ut/jacoco.xml"
#peer-review:
  #steps: