name: qa

on:
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
    - run: java -version 
    - run: mvn clean install test
    
    
    
#code-coverage:
  #steps: "diff-cover target/jacoco-ut/jacoco.xml"
#peer-review:
  #steps:
