name: qa

on:
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: java setup
      uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
        
    - name: build and test
      run: mvn clean install test
    
    - name: diff-cover
      id: diff
      uses: Levias13/diff-cover-action@v1
      with:
       path: ${{ github.workspace }}/target/jacoco-ut/jacoco.xml
    - name: ver output
      run: echo "el resultado fue ${{ steps.diff.outputs.exit-code }}"
