name: qa

on:
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
    - run: java -version 
    - run: mvn clean install test
    
  code-coverage:
   name: Code coverage
   runs-on: ubuntu-latest
   steps:
   - uses: madrapps/jacoco-report@v1.1
     with:
      path: ${{ github.workspace }}/target/reports/jacoco-ut/jacoco.xml
      token: ${{ secrets.GITHUB_TOKEN }}
      min-coverage-overall: 0
      min-coverage-changed-files: 60
