name: qa

on:
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - run: mvn clean install test
    
#code-coverage:
  #steps: "diff-cover target/jacoco-ut/jacoco.xml"
#peer-review:
  #steps:
